baseURL = 'https://DDRG.codeberg.page/'
locale = 'es-es'
title = "DDRG | Digital Forensics & OSINT Analyst"

[module]
  [[module.imports]]
    path = "go.ngs.io/hugo-primer-blog"

theme = "hugo-primer-blog"

[params]
  sidebar = true             # Activa la barra lateral (estilo técnico GitHub)
  recentPostsCount = 5       # Muestra tus últimos tutoriales en la barra lateral
  defaultTheme = "dark"      # Forzamos modo oscuro por defecto (preferido en ciberseguridad)
  showReadingTime = false    # Oculta el tiempo de lectura para un look más limpio
  showAuthor = true

  # Color principal estilo terminal/seguridad (Verde hacker o Azul corporativo)
  primaryColor = "#2ea44f"   # Verde técnico de GitHub

  # Configuración de tus enlaces profesionales
  [params.social]
    github = ""                # Lo dejamos vacío para desactivar el enlace automático a GitHub

# Configuración del Menú Profesional
[menus]
  [[menus.main]]
    name = "Whoami"
    url = "/whoami/"
    weight = 1

  [[menus.main]]
    name = "Directorio DFIR/OSINT"
    url = "/tools/"
    weight = 2

  [[menus.main]]
    name = "Tutoriales"
    url = "/tutoriales/"
    weight = 3

